/* bin2c.c -- tiny build-time tool: reads a binary file and writes a C
 * source file defining it as a byte array + length. Used to compile the
 * gui/blobs files (a fixed function of the patch/ sources, cross-compiled
 * by build_blobs.sh) directly into the GUI binary instead of shipping them
 * as loose sibling files -- makes headrush-nam-gui/gui-core-cli fully
 * self-contained single-file executables. Deliberately plain C with no
 * platform-specific code (runs as a host tool on every build machine,
 * including under a mingw-w64 cross toolchain).
 *
 * Usage: bin2c <input-file> <output.c> <symbol-name>
 */
#include <stdio.h>

int main(int argc, char** argv)
{
  if (argc != 4)
  {
    fprintf(stderr, "usage: %s <input-file> <output.c> <symbol-name>\n", argv[0]);
    return 1;
  }
  const char* in_path = argv[1];
  const char* out_path = argv[2];
  const char* symbol = argv[3];

  FILE* in = fopen(in_path, "rb");
  if (!in)
  {
    fprintf(stderr, "bin2c: opening %s failed\n", in_path);
    return 1;
  }
  FILE* out = fopen(out_path, "w");
  if (!out)
  {
    fprintf(stderr, "bin2c: opening %s for write failed\n", out_path);
    fclose(in);
    return 1;
  }

  fprintf(out, "/* generated by gui/tools/bin2c.c from %s -- do not edit */\n", in_path);
  fprintf(out, "const unsigned char %s[] = {\n", symbol);

  unsigned char buf[4096];
  size_t n;
  unsigned long total = 0;
  int col = 0;
  while ((n = fread(buf, 1, sizeof(buf), in)) > 0)
  {
    for (size_t i = 0; i < n; ++i)
    {
      fprintf(out, "0x%02x,", buf[i]);
      if (++col == 16)
      {
        fputc('\n', out);
        col = 0;
      }
    }
    total += (unsigned long)n;
  }
  if (col != 0)
    fputc('\n', out);
  fprintf(out, "};\n");
  fprintf(out, "const unsigned long %s_len = %luUL;\n", symbol, total);

  fclose(in);
  fclose(out);
  return 0;
}
